import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/header";
import { CartProvider } from "@/data/contexts/cartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Shop website",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="pt-br">
         <body className={inter.className}>
            <CartProvider>
               <Header />
               {children}
            </CartProvider>
         </body>
      </html>
   );
}
